name: ascii-generation workflow
on: push
jobs:
    ascii_job:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v2
            - name: executing shell-script
              run: |
                chmod +x ascii-script.sh
                ./ascii-script.sh
              
            - name: list repo files
              run: ls -la
              
            