name: my-first cicd pipeline
on: push
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: cicd pipeline
              run: echo "hello, cicd pipeline"
            - name: checkout code
              uses: actions/checkout@v2
            - name: list the files
              run: ls -la
            - name: print current directory
              run: pwd
            