name: executing multiple jobs
on: push
jobs:
    build-job1:
        runs-on: ubuntu-latest
        steps:
            - name: inastall cowsay program
              run: sudo apt-get install -y cowsay
            - name: execute cowsay
              run: cowsay -f dragon "run for a cover, i am a dragon" >> dragon.txt
            - name: upload dragon text file
              uses: actions/upload-artifact@v3
              with:
                name: dragon text file
                path: dragon.txt
    test-job2:
        needs: build-job1
        runs-on: ubuntu-latest
        steps:
            - name: download the dragon text file
              uses: actions/download-artifact@v3
              with:
                name: dragon text file
            - name: test the file exists
              run: grep -i "dragon" dragon.txt
    deploy-job3:
        needs: test-job2
        runs-on: ubuntu-latest
        steps:
            - name: download the dragon text file
              uses: actions/download-artifact@v3
              with:
                name: dragon text file
            - name: read the file
              run: cat dragon.txt
            - name: deploy the file
              run: echo "deploying........"
    
