name: executing multiple jobs
on: push
jobs:
    build-job1:
        runs-on: ubuntu-latest
        steps:
            - name: inastall cowsay program
              run: sudo apt get install -y cowsay
            - name: execute cowsay
              run: cowsay -f dragon "run for a cover, i am a dragon" >> dragon.txt
            - name: sleep for 30 seconds
              run: sleep 30
    test-job2:
        runs-on: ubuntu-latest
        steps:
            - name: sleep for 10 seconds
              run: sleep 10
            - name: test the file exists
              run: grep -i "dragon" dragon.txt
    deploy-job3:
        runs-on: ubuntu-latest
        steps:
            - name: read the file
              run: cat dragon.txt
            - name: deploy the file
              run: echo "deploying........"
    
